version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - marriageApi
      - wedding-frontend

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8083:80"
    networks:
      - mynetwork
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

  marriageApi:
    image: ghcr.io/romankuroptev/marriageapi:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=mydatabase;Username=postgres;Password=mysecretpassword
    networks:
      - mynetwork
    depends_on:
      - db

  wedding-frontend:
    image: ghcr.io/romankuroptev/marriageapp-wedding-frontend:latest
    build:
      context: ./wedding-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - mynetwork
    volumes:
      - ./wedding-frontend:/app
      - ./wedding-frontend/node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:8080

networks:
  mynetwork:

volumes:
  pgadmin_data:
  db_data: